feat: Adding EventPayloadFunction for sendFinishEvent
keptn-sandbox/keptn-jenkins-library pull request #105
Opened 2022-03-29 17:00 UTC by reneforstner

Within this PR keptn.sendFinishedEvent takes an additional parameter "eventPayload"
this parameter takes a map and put it in the json body which is sent to keptn.

Why we've implemented this:
currently we are not able to enrich a sendFinishedEvent with the respective event payload.
If a sendFinishedEvent eventType:"test" is sent without start & end timestamps, keptn fails an upcoming evaluation task due to missing parameters.

The function is implemented in a manner that it takes the "eventType" parameter as the name for the json object.

2022-03-30 06:37 UTC, christian-kreuzberger-dtx commented on README.md
> +// keptn.sendFinishEvent functions have optional event payload - example payload for keptn.sendFinishEvent eventType: "test"
should be "keptn.sendFinishedEvent", not "keptn.sendFinishEvent"

2022-03-30 06:37 UTC, christian-kreuzberger-dtx commented on README.md
> +// keptn.sendFinishEvent functions have optional event payload - example payload for keptn.sendFinishEvent eventType: "deployment"
Same here, "Finish" vs. "Finished"

2022-03-30 06:37 UTC, christian-kreuzberger-dtx commented on README.md
> +eventPayload.put('deploymentURIsLocal', ['carts.sockshop-staging.svc.cluster.local','another.cartsuir.local'])
did you mean "another.cartsUri.local"?

2022-03-30 06:41 UTC, christian-kreuzberger-dtx commented on README.md
> +def keptnContext = keptn.sendStartEvaluationEvent starttime:"2019-06-07T07:00:00.0000Z", endtime:"2019-06-07T08:00:00.0000Z", labels: labels, eventPayload: eventPayload
Not sure if this is the correct example here? This example refers to `sendStartEvaluationEvent` and not `sendFinishedEvent`

2022-03-30 06:41 UTC, christian-kreuzberger-dtx commented on src/sh/keptn/Keptn.groovy
> +    def eventPayload = args.containsKey('eventPayload') ? args.eventPayload : [:]
Question: Should we call it `eventTypePayload` instead of `eventPayload` for consistency?

2022-03-30 06:43 UTC, christian-kreuzberger-dtx commented on src/sh/keptn/Keptn.groovy
> +def addEventTypePayload(requestBody, eventType, eventPayload) {
Also here, should we call it `eventTypePayload` instead of `eventPayload` for consistency?

2022-03-30 06:45 UTC, christian-kreuzberger-dtx requested changes
Thank you for your contribution.

Your PR cannot be merged at the moment, because two check are failing:

1. Your commit(s) need to have a signoff (`git commit -s`) to fullfil the Developers Certificate of Origin (DCO). You can find more information here: https://github.com/keptn-sandbox/keptn-jenkins-library/pull/105/checks?check_run_id=5741585884
2. Semantic PR validiation fails (PR title needs to have a specific format) - this one is easy to fix though, just change the title of your PR to "feat: Adding EventPayloadFunction for sendFinishEvent"

In addition, I have left some comments in the README and in the source-code. The implementation itself looks perfect, just some naming issues.

Please let us know if you need help with that.

2022-04-27 11:55 UTC, grabnerandi commented
HI. I also had a quick look at this PR after seeing the implementation in action at the last Keptn User Group.
I think this is the first step towards enabling our "Modernizing your Jenkins Pipeline" Use Case where we allow our users to break their larger jenkins pipelines into smaller components.

I suggest to merge this PR but probably have some future ideas which have also been brought up by the community:
- provide the same functionality of passing custom metadata when triggering a sequence from Jenkins

2022-04-27 12:06 UTC, reneforstner commented
> HI. I also had a quick look at this PR after seeing the implementation in action at the last Keptn User Group. I think this is the first step towards enabling our "Modernizing your Jenkins Pipeline" Use Case where we allow our users to break their larger jenkins pipelines into smaller components.
> 
> I suggest to merge this PR but probably have some future ideas which have also been brought up by the community:
> 
>     * provide the same functionality of passing custom metadata when triggering a sequence from Jenkins

This could be also implemented with the raised issue #45 
Having a helper function for generating cloud events, which takes an eventTypePayload parameter (as it is currently implemented within this PR for the sendFinishedEvent). If anyone calls the function for triggering a sequence the eventTypePayload array just gets the additional data required to trigger the correct sequence

2022-04-28 11:26 UTC, christian-kreuzberger-dtx approved these changes
Thanks, LGTM

2022-04-28 11:26 UTC, merged